### PR TITLE
deps(bump): use new Bump CLI instead of legacy ruby gem

### PR DESCRIPTION
**Pull request by paulRbr**
Hi folks!

We've released a brand new CLI to interact with Bump.sh this week. We
thought you would be interested in using it in your OpenAPI spec
repository to avoid having an additionnal Ruby dependency.

Please let us know if you have any specific needs with our new CLI so
we can improve it.

Many thanks,
Paul from Bump.sh

-------

## Description of the change

- Remove the ruby dependency (`Gemfile`) and add new `bump-cli` in node dependencies (`package.json`)
- Adapt the README to remove mention of legacy ruby gem
- Use new bump-cli to `preview` the main `openapi.json` entrypoint (via `npm run preview`) _(External references all work as expected directly on Bump now)ç

## Type of change

- Chore dependencies update

### CODE REVIEW

**Comment by dangdennis** [comment]
Oh heck yeah!

**Comment by ps2-controller** [comment]
Awesome -- yeah @dangdennis , I'll test it out first thing tomorrow

**Comment by dangdennis** [comment]
Thanks alot @paulRbr

**Comment by paulRbr** [comment]
Hi folks, I've rebased the branch to resolve conflicts with your latest changes on `master`. :slightly_smiling_face:

**Comment by dangdennis** [comment]
Thank you @paulRbr ! We haven't gotten to this yet but certainly will end of week.

**Comment by ps2-controller** [comment]
Thanks @paulRbr ! Looks great!

**Pull request merged**
