### PR TITLE
CAN-333: updated payment post endpoints to show the correct line item type

### PR DESCRIPTION
**Pull request by alexcanopy**
Small discrepancy in our api doc examples where all of our POST line item example responses (manual fee, payment, debit and credit offset) are showing a response line_item_type of 'CHARGE', even though this value would vary as to the type of POST that is performed (eg. POST payment will return a line_item_type of 'PAYMENT')

### CODE REVIEW

**Review by dangdennis — COMMENTED** [review]
I think this makes sense. It's a bit unfortunate we duplicate a line item schema so often. Is there a way to concisely say "hey this is a line item schema but this particular line item type is ONLY payment, charge, debit offset, credit offset"?

**Comment by alexcanopy** [comment]
One more important change: The current POST manual fee line item succes response in the docs was using a different schema (schema/ResponseLineItem.json) than the other line items responses (LineItem.json). I wasn't seeing the ResponseLineItem.json schema being followed by the manual fee post, so I updated the manual fee post response to be in line with the other line item schemas.

**Comment by alexcanopy** [comment]
I'll look into it - these files are effectively children of the basic lineitem schema. I think I saw some capability for inheritance between schemas, that might do the trick.

**Comment by alexcanopy** [comment]
New model is to have a BaseLineItem schema for all properties common to all line item responses. Then, in line item responses, each different line item type (payments, charges, etc.) will have custom  line_item_overview object based on the API's output

**Review by dangdennis — COMMENTED** [review]
consider adding `line_item_overview` at the top leve lof each specialized LI overview object

**Review by dangdennis — APPROVED** [review]

**Pull request merged**
