### PR TITLE
Get cards route and scope cards API

### PR DESCRIPTION
**Pull request by kpamaran**
## Description of the change

Required for https://github.com/canopy1/canopy-api/pull/929

New:
- GET /accounts/{account_id}/cards route
- More documentation on substructures for non-Lithic issuer processor details in cards routes

Breaking Changes:
- Move /accounts/{account_id}/customers/{customer_id}/cards endpoints to  /accounts/{account_id}/cards to avoid overloading the customer entity as a cardholder. Cards can still be associated with customers if desired but it is no
longer required.
- POST/PUT routes return a single customer object instead of a result-set
- Remove card details from responses with customer account data

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]()

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Review by ps2-controller — APPROVED** [review]
Does this eliminate our ability to know what card belongs to which customer on the account?

**Comment by kpamaran** [comment]
@ps2-controller

We always know which customer the card belongs to because it's always the first assigned customer in the case of Lithic.

**Comment by ps2-controller** [comment]
@kpamaran --- but if they have two customers and they call 
https://docs.canopyservicing.com/#operation-post-accounts-parameter-customers-parameter-cards

once for each customer, it'll be assigned to two separate customers, not the first assigned customer, right?

**Comment by kpamaran** [comment]
@ps2-controller oh I misinterpreted. It is the first customer's information that is used to create a subaccount in Lithic, but afterwards our system will keep track of which customer a card was creating for.

**Pull request closed without merging**
