### PR TITLE
CAN-349 expanded line_item_statuses enum

### PR DESCRIPTION
**Pull request by alexcanopy**
Moved line_item_status to a separate schema internally. Added enum for line_item_status with all possible line_item_status values for requests and responses

https://linear.app/canopy-inc/issue/CAN-349/bug-line-item-statuses-not-enumerating-possible-returned-values

### CODE REVIEW

**Review by dangdennis — APPROVED** [review]
nice

**Comment by ps2-controller** [comment]
@alexcanopy , is there a way to preserve the distinct status types for each line item?

**Comment by ps2-controller** [comment]
Previously, the input enum for payments was unique to inputs we'd expect for payments, same with charges, etc --- this looks like it aggregates all the input enums and says you can use any of them for any line item type

**Comment by ps2-controller** [comment]
i.e. previously the `CreatePayment` input looked like:
```
"enum": ["VALID", "INVALID", "PENDING", "AUTHORIZED"],
```
but now it looks like 

```
     "enum": [
        "AUTHORIZED",
        "DECLINED",
        "INVALID",
        "OFFSET",
        "PENDING",
        "POSTED",
        "REVERSED",
        "ROLLED",
        "SETTLED",
        "SPLIT_INVALID",
        "SPLIT_VALID",
        "VALID",
        "VOID"
      ],
```

but most of those statuses in that second list should never be part of the create payment input

**Comment by alexcanopy** [comment]
@ps2-controller  that's makes a lot of sense - to handle this, I am thinking we can create a second  create line_item_status schema with statuses that make sense for users to pass via a create line item operation

`"enum": ["VALID", "INVALID", "PENDING", "AUTHORIZED"],`

Then have a separate line item edit and responses schema to show the full list of line item statuses that can be returned.

**Comment by dangdennis** [comment]
> > @ps2-controller that's makes a lot of sense - to handle this, I am thinking we can create a second create line_item_status schema with statuses that make sense for users to pass via a create line item operation
> > `"enum": ["VALID", "INVALID", "PENDING", "AUTHORIZED"],`
> > Then have a separate line item edit and responses schema to show the full list of line item statuses that can be returned.
> 
> Edit should still be different than the response since many from our "response" are system-generated line item statuses, not customer input.
> 
> Hmm.... okay so there are a few tradeoffs in that approach still:
> 
>     * it only allows for differences in input / edit / response schemas, _not_ differences across `line_item_type`
> 
>     * In reality, there are different input schemas for `payments`, `fees`, `charges`, etc -- and there's a good chance these will further diverge over time.
> 
> 
> So this refactor to consolidate line item input schemas may temporarily reduce schema complexity, but it does so at the expense of accounting for differences across line_item_types.
> 
>     * At the moment, this tradeoff maaaayyyy be worth it, as the input types are close enough (though they still diverge a bit)
> 
>     * Over time though, if the `create_payment` input starts to look more and more different than the `create_charge` input, it'll get more and more confusing to the caller if we try to box them into a generalized schema

Agreed then. It would be cool. Internally and in our learning docs, we may return the entire set of enums for line items. But POST operations are more unique to each their own.

**Comment by alexcanopy** [comment]
If the reality is that each line item schemas can diverge, we should keep them separate. Unfortunately I think that means we should undo the general line item status response - this would only really applicable for the generic line item getter. Otherwise, each successful individual line item post response would be restricted to the values that can be passed in.

**Review by dangdennis — APPROVED** [review]

**Pull request merged**
