### PR TITLE
Feature external account

### PR DESCRIPTION
**Pull request by ps2-controller**
## Description of the change

-- allows for an optional `external_account_id` to be passed with the account.
-- this gets set in the database and can be used to resolve the account to an account in an external system.
-- backwards compatible

### CODE REVIEW

**Review by dangdennis — APPROVED** [review]

**Comment by dangdennis** [comment]
We'll need to bump npm version to align the types later, but all good for now.

**Comment by ps2-controller** [comment]
cool, we do that when deploying QA -> RC right?

**Comment by dangdennis** [comment]
Yes, or you can do a prerelease+prefix so our internal codebase can use it too across teams. Did npm link work for you fine?

**Review by vikram-canopy — COMMENTED** [review]
LGTM

**Pull request merged**
