### PR TITLE
Uplift add more privacy data

### PR DESCRIPTION
**Pull request by ps2-controller**
card tokens in external IDs
card token per line item
account token as well (privacy)

### CODE REVIEW

**Comment by dangdennis** [comment]
Is this something we still want to merge? Does it need updates?

**Comment by ps2-controller** [comment]
@kpamaran 

Hmm, I think given that it lives nested within a privacy object, this type of abstraction removes clarity. Imo we should try to provide as much specificity as possible within the privacy object, so the developer can tell very easily what the exact privacy config is.
The key purpose of nesting each new issuer processor type as its own object is so we don't have to guess at generic parameter names that try to capture all future integrations

**Comment by kpamaran** [comment]
I think it depends on which perspective is taken, for developers who are using our integration and have not read the issuing API for the integration a term `external_card_id` makes it clear the value is sourced outside, versus `card_token` it requires a person to know the issuing API well enough to make the association.

On the flip side, if they are familiar then it's clear

**Comment by kpamaran** [comment]
https://canopy-corp.slack.com/archives/C01608B94E8/p1620053811001500

Going with `x_token` !

Assumptions being
- majority of orgs will only concern themselves with a single issuer
- make it clear that `issuer_processor_details` only has external values

**Review by kpamaran — APPROVED** [review]

**Pull request merged**
